### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by kalouantonis** [bluddy/ocamlverse#10]
Should this project have a license? I suppose if we were on a Wiki we wouldn't need one, but since we're on github I feel like it should be there.

I'd be privy to go with something liberal like `MIT` or `BSD`.

**Comment by bluddy** [comment]
Dang, I really know so little about licenses. What's the downside of not having one?

**Comment by bluddy** [comment]
Ah ok. A quick google search showed that without a license we have default copyright rights. Sure thing -- whichever you prefer.

**Comment by kalouantonis** [comment]
Well, it just makes it easier for people to contribute to the project AFAIK. Its clear who owns what and what the liability of each person involved is. 

Github created https://choosealicense.com/ to help with deciding on which one to use. [This](https://choosealicense.com/non-software/#data-media-etc) page might be more useful since it talks about documentation and media specifically.

**Comment by bluddy** [comment]
I guess CC0-1.0 looks good, and so does MIT. Any opinions?

**Comment by kalouantonis** [comment]
I'd probably go with CC0-1.0 ([link for the lazy](https://choosealicense.com/licenses/cc0-1.0/)). Github recommends we use that for non-software projects and I'm not a lawyer so I'll just take their word on it.

**Comment by bluddy** [comment]
Done. Thanks -- I wouldn't have thought of this.

**Comment by bluddy** [comment]
I went ahead and added you as collaborator. Hope that's ok.

**Comment by kalouantonis** [comment]
Awesome, thanks!

**Comment by pmetzger** [comment]
Creative Commons is my preference too, but there are several CC choices (like whether we require attribution or whether we prevent commercial use.) I'd suggest the least restrictive possible. Maybe even CC-0.

**Comment by kalouantonis** [comment]
We ended up deciding on CC-0.
