### ISSUE TITLE
Add a page for example projects

### ISSUE THREAD

**Issue by kalouantonis** [bluddy/ocamlverse#13]
It would be nice to have a page where some example projects of various types are displayed. For example, it would be handy to have examples for web apps, CLI utils, etc. 

I usually find this quite useful when I'm learning a new language observing "well designed" projects to see how they're implemented.

**Comment by kalouantonis** [comment]
I found a somewhat decent source [here](https://www.lri.fr/~filliatr/software.en.html).

**Comment by kalouantonis** [comment]
We can use this page as a starting point: https://www.lri.fr/~filliatr/software.en.html

**Comment by bluddy** [comment]
Great idea. Probably makes sense to put it under Learning.

**Comment by pmetzger** [comment]
@kalouantonis Go for it!

**Comment by kalouantonis** [comment]
I'm on it, PR coming soon...
